
export const Temtem  = {
    number:                    "",
    name:                      "",
    types:                     [""],
    portraitWikiUrl:           "",
    lumaPortraitWikiUrl:       "",
    wikiUrl:                   "",
    stats:                     [""],
    traits:                    [""],
    details:                   "",
    techniques:                [],
    trivia:                    [],
    evolution:                 "",
    wikiPortraitUrlLarge:      "",
    lumaWikiPortraitUrlLarge:  "",
    locations:                 [],
    icon:                      "",
    lumaIcon:                  "",
    genderRatio:               "",
    catchRate:                 "",
    hatchMins:                 "",
    tvYields:                  "",
    gameDescription:           "",
    wikiRenderStaticUrl:       "",
    wikiRenderAnimatedUrl:     "",
    wikiRenderStaticLumaUrl:   "",
    wikiRenderAnimatedLumaUrl: "",
    renderStaticImage:         "",
    renderStaticLumaImage:     "",
    renderAnimatedImage:       "",
    renderAnimatedLumaImage:   "",
}
